config/routes.rb
SsCleaners::Application.routes.draw do
  root :to => "pages#home"

  get "about" => "pages/about"

  get "contact" => "pages/contact"

  get "prices" => "pages/prices"

  get "coupons" => "pages/coupons"

  get "location" => "pages/location"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def prices
  end

  def coupons
  end

  def location
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "Spic N' Span Cleaners", "#" %>
    by <%= link_to "Brian Han", "www.brianyhan.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">OMRails</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                          <%= link_to 'Home',  root_path %>
                        	</li>
                        <li>    
                          <%= link_to 'About',  about_path %>
                        	</li>
                        <li>
                        	<%= link_to "Contact", contact_path %>
                        	</li>
                        <li>
                        	<%= link_to "Coupons", coupons_path %>
                        	</li>
                        <li>
                        	<%= link_to "Location", location_path %>
	                        </li>
                        <li>
                        	<%= link_to "Prices", prices_path %>
  	                      </li>
                    </ul>
                    <ul class="nav pull-right">
                                <li><%= link_to 'Login',  '#' %></li>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spic N' Span Cleaners</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
    <%= yield %>

    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Spic N' Span Cleaners</h1>
<p>
  
</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/coupons.html.erb
<h1>Pages#coupons</h1>
<p>Find me in app/views/pages/coupons.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome to Spic N' Span Cleaners!</h1>
<p>
  You've found the home page for the best Dry Cleaners in Orange County!
</p>
<p>Dry Cleaning for a Dry Summer! All 1st timers get 20% off!
  <%= link_to "DEAAALS!", coupons_path %>
</p>

app/views/pages/location.html.erb
<h1>Pages#location</h1>
<p>Find me in app/views/pages/location.html.erb</p>

app/views/pages/prices.html.erb
<h1>Pages#prices</h1>
<p>Find me in app/views/pages/prices.html.erb</p>